version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/ConsoleApp1"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    target-branch: "main"
    labels:
      - "nuget dependencies"
      - "dependabot"
      - "minor"
  - package-ecosystem: "nuget"
    directory: "/ConsoleApp2"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    target-branch: "main"
    labels:
      - "nuget dependencies"
      - "dependabot"
      - "minor"
